### PR TITLE
refactor: add null safety

### PR DESCRIPTION
**Pull request by tnc1997**
Thank you very much for your work on this package @pepsighan.

I am hoping that it might be possible to release a null safe version.

### CODE REVIEW

**Comment by pepsighan** [comment]
Awesome, thanks for the PR. The PR changes look good to be merged.

**Comment by pepsighan** [comment]
I have pushed the new version at https://pub.dev/packages/mdi/versions/5.0.0-nullsafety.0. Thanks for your effort.

**Comment by tnc1997** [comment]
Thank you for pushing up that version, I can confirm that it is working perfectly!

**Comment by PiotrWpl** [comment]
Hi @pepsighan any date when this will be released as stable version?

**Pull request merged**
